research:
  tier1:
    global:
      playtime: 90 #minutes
      xp: 10 #Levels
    strength:
      playtime: 90
      xp: 5
    health:
      playtime: 90
      xp: 5
      maxhealth: 24
    fireresistance:
      playtime: 120
      xp: 5
    haste:
      playtime: 150
      xp: 5
    speed:
      playtime: 90
      xp: 5
    invisibility:
      playtime: 90
      xp: 5
  tier2:
    global:
      playtime: 240
      xp: 20
    strength:
      playtime: 240
      xp: 10
      timeactive: 10 #in minutes
    health:
      playtime: 260
      xp: 10
      timeactive: 10
      maxhealth: 30
    fireresistance:
      playtime: 260
      xp: 10
      timeactive: 10
    haste:
      playtime: 240
      xp: 10
      timeactive: 10
    speed:
      playtime: 240
      xp: 10
      timeactive: 10
    invisibility:
      playtime: 240
      xp: 10
      timeactive: 10
  tier3:
    global:
      playtime: 300
      xp: 40
      timeactive: 15
    strength:
      playtime: 300
      xp: 15
      timeactive: 15
    health:
      playtime: 300
      xp: 15
      timeactive: 15
      maxhealth: 34
    fireresistance:
      playtime: 300
      xp: 15
      timeactive: 15
    haste:
      playtime: 300
      xp: 15
      timeactive: 15
    speed:
      playtime: 300
      xp: 15
      timeactive: 15
    invisibility:
      playtime: 300
      xp: 15
      timeactive: 15

totem-colors:
  strength: WHITE
  health: RED
  fireresistance: RED
  haste: GOLD
  speed: AQUA
  invisibility: WHITE

potion-settings:
  strength:
    enabled: true
  health:
    enabled: true
  fireresistance:
    enabled: true
  haste:
    enabled: true
  speed:
    enabled: false
  invisibility:
    enabled: false